Exercise1/Controllers/ESLNotificationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Exercise1.Models;
using Newtonsoft.Json;
using System.IO;
using System.Net;
using System.Diagnostics;
using Exercise1.Controllers;
using Silanis.ESL.SDK;
using Silanis.ESL.SDK.Builder;
using System.Text;
using Exercise1.Database;
using Exercise1.Services;

namespace Exercise1.Controllers
{
    public class ESLNotificationsController : Controller
    {
        static NotificationsDatabase database = NotificationsDatabase.getInstance;

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

  
        [HttpPost]
        public void Index(ESLNotificationsModel notification)
        {
            //TODO: Uncomment the logging statement below and deploy your application to the cloud and see it in action!
            //Trace.WriteLine("Notification " + notification.name +  " for package " + notification.packageId + " received");

            ESLNotificationsService svc = new ESLNotificationsService();
            svc.saveNotifications(notification);

            Response.ClearContent();
            Response.StatusCode = (int)HttpStatusCode.NoContent;
        }

        //Displays the e-SignLive event notifications
        //Displays the status of the packages
        [HttpGet]
        public ActionResult Dashboard()
        {
            Dictionary<String, String> updatedDatabase = database.getFromDatabase();
            if (updatedDatabase.Count == 0)
            {
                Trace.WriteLine("No packages to view..Please create a package.");
            }

            Trace.WriteLine("DB entries below:");
            foreach (var entry in updatedDatabase)
            {
                Trace.WriteLine("Package ID: " + entry.Key + " Status: " + entry.Value);
            }

            ViewData["updatedDatabase"] = updatedDatabase;
            return View();
        }
    }
}

Exercise1/Controllers/InsuranceFormController.cs
using Silanis.ESL.SDK;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Exercise1.Services;
using Exercise1.Models;

namespace Exercise1.Controllers
{
    public class InsuranceFormController : Controller
    {
        //
        // GET: /InsuranceForm/
        //Displays the "Insurance Form Page" of the insurance company web application  
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(PropertiesFile properties)
        {
            String API_KEY = properties.API_KEY;
            String BASE_URL = properties.BASE_URL;
            String AUTO_SUBMIT_URL = properties.AUTO_SUBMIT_URL;

            if (!string.IsNullOrEmpty(API_KEY))
            {
                HttpContext.Session["API_KEY"] = API_KEY;
            }

            if (!string.IsNullOrEmpty(BASE_URL))
            {
                HttpContext.Session["BASE_URL"] = BASE_URL;
            }

            if (!string.IsNullOrEmpty(AUTO_SUBMIT_URL))
            {
                HttpContext.Session["AUTO_SUBMIT_URL"] = AUTO_SUBMIT_URL;
            }

            if (String.IsNullOrEmpty(API_KEY) || String.IsNullOrEmpty(BASE_URL) || String.IsNullOrEmpty(AUTO_SUBMIT_URL))
            {
                throw new SystemException("Please fill in the properties file on the homepage. One or more entries are null");
            }
            return View();
        }

        [HttpPost]
        public ActionResult ESLSignature(InsuranceFormModel form)
        {
            string API_KEY =  (string) HttpContext.Session["API_KEY"];
            string BASE_URL = (string) HttpContext.Session["BASE_URL"];
            string AUTO_SUBMIT_URL = (string)HttpContext.Session["AUTO_SUBMIT_URL"];

            // Create a packageId 
            PackageId packageId = ESLPackageCreation.createPackage(form, API_KEY, BASE_URL, AUTO_SUBMIT_URL);

            //Get the session token 
            SessionToken token = ESLPackageCreation.createSessionToken(packageId, API_KEY, BASE_URL);

            ViewData["token"] = token.Token;

            // Redirect the signer to e-SignLive
            return View();
        }

	}
}

Exercise1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -.NET e-SL Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.1/js/bootstrapValidator.min.js"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.1/css/bootstrapValidator.min.css" />

        </head>
        <body>
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                        </button>
                        @Html.ActionLink(".NET e-SL Application", "Index", "Home", null, new { @class = "navbar-brand" })
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Insurance Form", "Index", "InsuranceForm")        </li>
                            <li>@Html.ActionLink("Notifications Dashboard", "Dashboard", "ESLNotifications")        </li>
                         </ul>
                    </div>
                </div>
            </div>
            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year        -.NET e-SL Application</p>
               </footer>
           </div>
           @RenderSection("scripts", required: false)
       </body>
       </html>